/**
 * Notepad language catalog — the single source of truth for
 * extension → language, language → default extension, dropdown entries and
 * status-bar labels.
 *
 * Only ids Monaco actually registers are used (see the `basic-languages`
 * folder + the json/css/html contributions), plus the pseudo-language
 * `swagger`, which drives the OpenAPI preview rather than tokenization.
 * Extensions are matched first-wins, so an extension claimed by an earlier
 * entry wins (e.g. `.yaml` stays YAML even though Swagger also saves as yaml).
 */
export interface LanguageDef {
  id: string;
  label: string;
  /** Extensions without the dot. The first one is used for Save defaults. */
  exts: string[];
  /** Exact lower-case file names (no extension needed) mapping here. */
  files?: string[];
  /** Listed in the Notepad language dropdown. */
  pickable?: boolean;
}

export const LANGUAGES: LanguageDef[] = [
  {
    id: 'plaintext',
    label: 'Plain Text',
    pickable: true,
    exts: [
      'txt',
      'text',
      'log',
      'out',
      'err',
      'csv',
      'tsv',
      'nfo',
      'diff',
      'patch',
      'srt',
      'vtt',
      'po',
      'pot',
      'pem',
      'crt',
      'cer',
      'csr',
      'asc',
      'gitignore',
      'gitattributes',
      'dockerignore',
      'npmignore',
      'eslintignore',
      'prettierignore',
      'http',
      'rest',
    ],
    files: ['license', 'notice', 'authors', 'copying'],
  },
  {
    id: 'markdown',
    label: 'Markdown',
    pickable: true,
    exts: ['md', 'markdown', 'mkd', 'mdown', 'mdwn', 'rmd'],
  },
  { id: 'mdx', label: 'MDX', pickable: true, exts: ['mdx'] },
  {
    id: 'json',
    label: 'JSON',
    pickable: true,
    exts: [
      'json',
      'jsonc',
      'json5',
      'jsonl',
      'ndjson',
      'geojson',
      'topojson',
      'jsonld',
      'webmanifest',
      'har',
      'ipynb',
      'avsc',
      'map',
      'code-workspace',
      'babelrc',
      'eslintrc',
      'prettierrc',
      'stylelintrc',
      'jshintrc',
      'swcrc',
      'tfstate',
    ],
  },
  {
    id: 'yaml',
    label: 'YAML',
    pickable: true,
    exts: ['yaml', 'yml', 'cff', 'yamllint'],
  },
  { id: 'swagger', label: 'Swagger/OpenAPI', pickable: true, exts: ['yaml'] },
  {
    id: 'xml',
    label: 'XML',
    pickable: true,
    exts: [
      'xml',
      'xsd',
      'xsl',
      'xslt',
      'wsdl',
      'svg',
      'rss',
      'atom',
      'rdf',
      'opml',
      'plist',
      'xaml',
      'csproj',
      'vbproj',
      'fsproj',
      'props',
      'targets',
      'nuspec',
      'resx',
      'storyboard',
      'xib',
      'kml',
      'gpx',
      'dtd',
      'jnlp',
      'mxml',
      'xul',
    ],
  },
  {
    id: 'html',
    label: 'HTML',
    pickable: true,
    exts: ['html', 'htm', 'xhtml', 'shtml', 'vue', 'svelte', 'astro'],
  },
  {
    id: 'handlebars',
    label: 'Handlebars',
    pickable: true,
    exts: ['hbs', 'handlebars', 'mustache'],
  },
  { id: 'pug', label: 'Pug / Jade', pickable: true, exts: ['pug', 'jade'] },
  { id: 'twig', label: 'Twig', exts: ['twig'] },
  { id: 'liquid', label: 'Liquid', exts: ['liquid'] },
  { id: 'razor', label: 'Razor', exts: ['cshtml', 'razor'] },
  { id: 'css', label: 'CSS', pickable: true, exts: ['css'] },
  { id: 'scss', label: 'SCSS', pickable: true, exts: ['scss', 'sass'] },
  { id: 'less', label: 'Less', pickable: true, exts: ['less'] },
  {
    id: 'javascript',
    label: 'JavaScript',
    pickable: true,
    exts: ['js', 'mjs', 'cjs', 'jsx', 'es6'],
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    pickable: true,
    exts: ['ts', 'tsx', 'mts', 'cts'],
  },
  {
    id: 'python',
    label: 'Python',
    pickable: true,
    exts: ['py', 'pyw', 'pyi', 'gyp', 'gypi'],
  },
  { id: 'java', label: 'Java', pickable: true, exts: ['java', 'jav'] },
  { id: 'kotlin', label: 'Kotlin', pickable: true, exts: ['kt', 'kts'] },
  { id: 'csharp', label: 'C#', pickable: true, exts: ['cs', 'csx'] },
  {
    id: 'cpp',
    label: 'C++',
    pickable: true,
    exts: ['cpp', 'cxx', 'cc', 'hpp', 'hxx', 'hh', 'ino', 'tpp'],
  },
  { id: 'c', label: 'C', pickable: true, exts: ['c', 'h'] },
  {
    id: 'objective-c',
    label: 'Objective-C',
    pickable: true,
    exts: ['m', 'mm'],
  },
  { id: 'go', label: 'Go', pickable: true, exts: ['go'] },
  { id: 'rust', label: 'Rust', pickable: true, exts: ['rs'] },
  {
    id: 'ruby',
    label: 'Ruby',
    pickable: true,
    exts: ['rb', 'rbw', 'gemspec', 'rake', 'ru', 'podspec'],
  },
  {
    id: 'php',
    label: 'PHP',
    pickable: true,
    exts: ['php', 'php3', 'php4', 'php5', 'phtml'],
  },
  { id: 'swift', label: 'Swift', pickable: true, exts: ['swift'] },
  { id: 'dart', label: 'Dart', pickable: true, exts: ['dart'] },
  { id: 'scala', label: 'Scala', pickable: true, exts: ['scala', 'sc', 'sbt'] },
  { id: 'perl', label: 'Perl', pickable: true, exts: ['pl', 'pm', 'pod'] },
  { id: 'lua', label: 'Lua', pickable: true, exts: ['lua'] },
  { id: 'r', label: 'R', pickable: true, exts: ['r'] },
  { id: 'julia', label: 'Julia', exts: ['jl'] },
  { id: 'elixir', label: 'Elixir', exts: ['ex', 'exs'] },
  { id: 'clojure', label: 'Clojure', exts: ['clj', 'cljs', 'cljc', 'edn'] },
  { id: 'coffeescript', label: 'CoffeeScript', exts: ['coffee', 'litcoffee'] },
  { id: 'fsharp', label: 'F#', exts: ['fs', 'fsi', 'fsx'] },
  { id: 'vb', label: 'Visual Basic', exts: ['vb', 'vbs', 'bas'] },
  { id: 'pascal', label: 'Pascal', exts: ['pas', 'pp', 'dpr'] },
  { id: 'scheme', label: 'Scheme', exts: ['scm', 'ss', 'rkt'] },
  { id: 'tcl', label: 'Tcl', exts: ['tcl'] },
  { id: 'sol', label: 'Solidity', exts: ['sol'] },
  { id: 'apex', label: 'Apex', exts: ['cls', 'trigger'] },
  { id: 'abap', label: 'ABAP', exts: ['abap'] },
  { id: 'bicep', label: 'Bicep', exts: ['bicep'] },
  { id: 'wgsl', label: 'WGSL', exts: ['wgsl'] },
  { id: 'systemverilog', label: 'SystemVerilog', exts: ['sv', 'svh'] },
  { id: 'verilog', label: 'Verilog', exts: ['v', 'vh'] },
  { id: 'qsharp', label: 'Q#', exts: ['qs'] },
  { id: 'typespec', label: 'TypeSpec', exts: ['tsp'] },
  { id: 'sparql', label: 'SPARQL', exts: ['rq'] },
  { id: 'cypher', label: 'Cypher', exts: ['cypher', 'cyp'] },
  { id: 'restructuredtext', label: 'reStructuredText', exts: ['rst'] },
  {
    id: 'shell',
    label: 'Shell',
    pickable: true,
    exts: [
      'sh',
      'bash',
      'zsh',
      'ksh',
      'ash',
      'bashrc',
      'bash_profile',
      'zshrc',
      'zshenv',
      'zprofile',
      'profile',
    ],
  },
  {
    id: 'powershell',
    label: 'PowerShell',
    pickable: true,
    exts: ['ps1', 'psm1', 'psd1'],
  },
  { id: 'bat', label: 'Batch', pickable: true, exts: ['bat', 'cmd'] },
  { id: 'sql', label: 'SQL', pickable: true, exts: ['sql', 'ddl', 'dml'] },
  { id: 'mysql', label: 'MySQL', exts: ['mysql'] },
  { id: 'pgsql', label: 'PostgreSQL', exts: ['pgsql'] },
  { id: 'redis', label: 'Redis', exts: ['redis'] },
  {
    id: 'ini',
    label: 'INI / TOML / Properties',
    pickable: true,
    exts: [
      'ini',
      'toml',
      'cfg',
      'conf',
      'properties',
      'env',
      'editorconfig',
      'npmrc',
      'yarnrc',
      'gitconfig',
      'gitmodules',
      'inf',
      'prefs',
      'desktop',
      'service',
      'flake8',
      'pylintrc',
    ],
  },
  {
    id: 'dockerfile',
    label: 'Dockerfile',
    pickable: true,
    exts: ['dockerfile'],
    files: ['dockerfile', 'containerfile'],
  },
  {
    id: 'hcl',
    label: 'Terraform / HCL',
    pickable: true,
    exts: ['hcl', 'tf', 'tfvars', 'nomad'],
  },
  {
    id: 'graphql',
    label: 'GraphQL',
    pickable: true,
    exts: ['graphql', 'gql', 'graphqls'],
  },
  { id: 'proto', label: 'Protocol Buffers', pickable: true, exts: ['proto'] },
];

/** Extra file names that map onto an existing language. */
export const EXTRA_FILENAMES: Record<string, string> = {
  gemfile: 'ruby',
  rakefile: 'ruby',
  podfile: 'ruby',
  brewfile: 'ruby',
  vagrantfile: 'ruby',
  fastfile: 'ruby',
  appfile: 'ruby',
  guardfile: 'ruby',
  capfile: 'ruby',
};
